export const FOLLOWING_ADD_LEAGUE = 'FOLLOWING_ADD_LEAGUE'
export const FOLLOWING_REMOVE_LEAGUE = 'REMOVE_LEAGUE_TO_FOLLOWING'
export const FOLLOWING_ADD_TEAM = 'FOLLOWING_ADD_TEAM'
export const FOLLOWING_REMOVE_TEAM = 'REMOVE_TEAM_TO_FOLLOWING'
